# Generated by Django 2.0.7 on 2018-07-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscstorageentry',
            name='value',
            field=models.TextField(),
        ),
    ]
