# Generated by Django 2.1 on 2018-08-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(default=-1)),
                ('value', models.BigIntegerField(default=-1000)),
                ('datetime', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
