# Generated by Django 2.1 on 2018-08-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerstation_graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='type',
            field=models.SmallIntegerField(db_index=True, default=-1),
        ),
    ]
