# Generated by Django 2.0.7 on 2018-07-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_online_stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsentry',
            name='id',
        ),
        migrations.AlterField(
            model_name='statsentry',
            name='nickname',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='statsentry',
            name='time',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='statsentry',
            name='uuid',
            field=models.CharField(db_index=True, max_length=36, primary_key=True, serialize=False),
        ),
    ]
