# Generated by Django 2.1 on 2018-08-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_online_stats', '0002_auto_20180712_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsentry',
            name='uuid',
            field=models.UUIDField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
