# Generated by Django 2.0.7 on 2018-07-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClanModel',
            fields=[
                ('order', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('cell_count', models.IntegerField(default=0)),
                ('is_in_council', models.BooleanField(default=False)),
            ],
        ),
    ]
